/* -------------------------------- Language Data -------------------------------- */
    const languageData = {
      "en": {
        "header_title": "CSR Initiative",
        "btn_register": "Register for <br>Scholarship",
        "info_para1": "EBCO is committed to improving the social and economic well-being of the community particularly carpenters and their families across India through its CSR initiatives. Our programs focus on skill development, financial security, and educational support, ensuring a brighter and more stable future for the carpenter community.",
        "skill-development-card-title": "Skill Development",
        "skill-development-card-para": "We help carpenters <strong>upgrade their skills</strong> and gain formal recognition for their existing expertise under Recognition of Prior Learning (RPL), who will get advance skill as well as <strong>certificate</strong>. ",
        "secured-future-card-title": "Secured Future",
        "secured-future-card-para": "To safeguard the lives and livelihoods of carpenters, we facilitate to get <strong>insurance coverage</strong> (Health and Accident) and would provide wage loss insurance in case of hospitalization.",
        "celebrate-excellence-card-title": "Celebrate Excellence",
        "celebrate-excellence-card-para": "We support the education of carpenters’ children by offering <strong>scholarships</strong> that encourage learning and reduce financial burden.",
        "info_para2": "We collaborate with credible NGOs for the design and execution of all CSR initiatives, ensuring quality, transparency, and high impact. To provide opportunities nationwide, we have created this digital platform, enabling carpenters to directly access and apply for EBCO CSR programs or someone else can nominate carpenters",
        "modal_title": "Register for the Scholarship",
        "modal-father-name": "Father's Name",
        "modal-father-mobile-number":"Father's Mobile Number",
        "modal-child-name":"Child's Name",
        "modal-child-school-name": "School Name",
        "modal-child-class": "Class",
        "modal-address-city": "City",
        "modal-address-state": "State",
        "modal-address-pincode": "Pin code",
        "modal-marksheet":"Upload Marksheet",
        "modal-admit-card":"Upload Admit Card",
        "modal-submit":"Submit",
        "footer_left": "© 2025 CSR Initiative | Powered by Ebco",
        "footer_contact": "Contact Us: abc@ebco.in",
        "footer_tollfree": "Toll-Free: 12345678900"
      },
      "hi": {
        "header_title": "सीएसआर पहल",
        "btn_register": "छात्रवृत्ति के लिए <br>पंजीकरण करें",
        "info_para1": "Ebco भारत भर में बढ़ईयों और उनके परिवारों के सामाजिक और आर्थिक कल्याण में सुधार के लिए प्रतिबद्ध है। हमारे कार्यक्रम कौशल विकास, वित्तीय सुरक्षा और शैक्षिक सहायता पर ध्यान केंद्रित करते हैं, जिससे बढ़ई समुदाय के लिए एक उज्जवल और अधिक स्थिर भविष्य सुनिश्चित होता है।",
        "skill-development-card-title": "कौशल विकास",
        "skill-development-card-para": "हम बढ़ईयों को <strong>अपने कौशल को उन्नत करने </strong>और पूर्व शिक्षा की पहचान (आरपीएल) के तहत उनकी मौजूदा विशेषज्ञता के लिए औपचारिक मान्यता प्राप्त करने में मदद करते हैं, जिन्हें उन्नत कौशल के साथ-साथ <strong>प्रमाणपत्र </strong>भी मिलेगा।",
        "secured-future-card-title": "सुरक्षित भविष्य",
        "secured-future-card-para": "बढ़ईयों के जीवन और आजीविका की सुरक्षा के लिए, हम <strong>बीमा कवरेज</strong> (स्वास्थ्य और दुर्घटना) प्राप्त करने में सुविधा प्रदान करते हैं और अस्पताल में भर्ती होने की स्थिति में वेतन हानि बीमा प्रदान करेंगे।",
        "celebrate-excellence-card-title": "उत्कृष्टता का जश्न",
        "celebrate-excellence-card-para": "हम बढ़ईयों के बच्चों की शिक्षा को <strong>छात्रवृत्तियाँ</strong> प्रदान करके समर्थन करते हैं जो सीखने को प्रोत्साहित करती हैं और वित्तीय बोझ को कम करती हैं।",
        "info_para2": "हम सभी सीएसआर पहलों के डिजाइन और निष्पादन के लिए विश्वसनीय गैर-सरकारी संगठनों के साथ सहयोग करते हैं, जो गुणवत्ता, पारदर्शिता और उच्च प्रभाव सुनिश्चित करते हैं। देशव्यापी अवसर प्रदान करने के लिए, हमने यह डिजिटल प्लेटफॉर्म बनाया है, जिससे बढ़ई सीधे Ebco सीएसआर कार्यक्रमों तक पहुंच सकते हैं और आवेदन कर सकते हैं या कोई और बढ़ईयों को नामांकित कर सकता है",
        "modal_title": "छात्रवृत्ति के लिए पंजीकरण करें",
        "modal-father-name": "पिता का नाम",
        "modal-father-mobile-number":"पिता का संपर्क नंबर",
        "modal-child-name":"बच्चे का नाम",
        "modal-child-school-name": "स्कूल का नाम",
        "modal-child-class": "कक्षा",
        "modal-address-city": "शहर",
        "modal-address-state": "राज्य",
        "modal-address-pincode": "पिन कोड",
        "modal-marksheet":"मार्कशीट अपलोड करें",
        "modal-admit-card":"एडमिट कार्ड अपलोड करें",
        "modal-submit":"जमा करें",
        "footer_left": "© 2025 CSR पहल | Ebco द्वारा संचालित",
        "footer_contact": "हमसे संपर्क करें: abc@ebco.in",
        "footer_tollfree": "टोल-फ्री: 12345678900"
      },
      "or": {
        "header_title": "ସିଏସଆର୍ ପଦକ୍ଷେପ",
        "btn_register": "ଛାତ୍ରବୃତ୍ତି ପାଇଁ <br>ପଞ୍ଜୀକରଣ କରନ୍ତୁ",
        "info_para1": "ଇବ୍କୋ ଭାରତର ବଢ଼େଇ ଏବଂ ସେମାନଙ୍କ ପରିବାରର ସାମାଜିକ ଓ ଅର୍ଥନୈତିକ କଲ୍ୟାଣ ପାଇଁ ପ୍ରତିବଦ୍ଧ। ଆମର କାର୍ଯ୍ୟକ୍ରମ କୌଶଳ ବିକାଶ, ଆର୍ଥିକ ସୁରକ୍ଷା ଏବଂ ଶିକ୍ଷାଗତ ସହାୟତା ଉପରେ ଗୁରୁତ୍ୱ ଦିଏ, ଯାହା ବଢ଼େଇ ସମୁଦାୟ ପାଇଁ ଏକ ଉଜ୍ଜ୍ୱଳ ଭବିଷ୍ୟତ ସୁନିଶ୍ଚିତ କରେ।",
        "skill-development-card-title": "କୌଶଳ ବିକାଶ",
        "skill-development-card-para": "ଆମେ ବଢ଼େଇମାନଙ୍କୁ <strong>ନିଜ କୌଶଳର ଉନ୍ନତି</strong> କରିବା ଏବଂ ପୂର୍ବ ଶିକ୍ଷାର ମାନ୍ୟତା (ଆର୍ପିଏଲ୍) ଅଧୀନରେ ସେମାନଙ୍କ ବିଶେଷଜ୍ଞତା ପାଇଁ ଆନୁଷ୍ଠାନିକ ମାନ୍ୟତା ହାସଲ କରିବାରେ ସାହାଯ୍ୟ କରୁଛୁ, ଯେଉଁମାନେ ଉନ୍ନତ କୌଶଳ ସହିତ ପ୍ରମାଣପତ୍ର ମଧ୍ୟ ପାଇବେ।",
        "secured-future-card-title": "ସୁରକ୍ଷିତ ଭବିଷ୍ୟତ",
        "secured-future-card-para": "ବଢ଼େଇମାନଙ୍କର ଜୀବନ ଏବଂ ଜୀବିକା ସୁରକ୍ଷିତ ରଖିବା ପାଇଁ, ଆମେ <strong>ବୀମା କଭରେଜ୍</strong> (ସ୍ୱାସ୍ଥ୍ୟ ଏବଂ ଦୁର୍ଘଟଣା) ପାଇବାରେ ସୁବିଧା ଦେଉଛୁ ଏବଂ ହସ୍ପିଟାଲ୍ରେ ଭର୍ତ୍ତି ହେଲେ ବେତନ କ୍ଷତି ବୀମା ପ୍ରଦାନ କରିବୁ।",
        "celebrate-excellence-card-title": "ଉତ୍କର୍ଷତା ପାଳନ",
        "celebrate-excellence-card-para": "ଆମେ ବଢ଼େଇମାନଙ୍କ ପିଲାମାନଙ୍କର ଶିକ୍ଷାକୁ <strong>ଛାତ୍ରବୃତ୍ତି</strong> ପ୍ରଦାନ କରି ସମର୍ଥନ କରୁଛୁ, ଯାହା ଶିକ୍ଷଣକୁ ଉତ୍ସାହିତ କରେ ଏବଂ ଆର୍ଥିକ ବୋଝ ହ୍ରାସ କରେ।",
        "info_para2": "ଆମେ ସମସ୍ତ ସିଏସଆର୍ ପଦକ୍ଷେପର ଡିଜାଇନ୍ ଏବଂ କାର୍ଯ୍ୟକାରିତା ପାଇଁ ବିଶ୍ୱାସଯୋଗ୍ୟ ଏନ୍ଜିଓ ସହିତ ସହଯୋଗ କରୁଛୁ, ଯାହା ଗୁଣବତ୍ତା, ସ୍ୱଚ୍ଛତା ଏବଂ ଉଚ୍ଚ ପ୍ରଭାବ ସୁନିଶ୍ଚିତ କରେ। ଦେଶବ୍ୟାପୀ ସୁଯୋଗ ପ୍ରଦାନ କରିବା ପାଇଁ, ଆମେ ଏହି ଡିଜିଟାଲ୍ ପ୍ଲାଟଫର୍ମ ତିଆରି କରିଛୁ, ଯାହା ବଢ଼େଇମାନଙ୍କୁ ସିଧାସଳଖ ଇବ୍କୋ ସିଏସଆର୍ କାର୍ଯ୍ୟକ୍ରମଗୁଡ଼ିକୁ ପ୍ରବେଶ କରିବା ଏବଂ ଆବେଦନ କରିବା ପାଇଁ ସକ୍ଷମ କରେ କିମ୍ବା ଅନ୍ୟ କେହି ବଢ଼େଇମାନଙ୍କୁ ନାମାଙ୍କନ କରିପାରିବେ।",
        "modal_title": "ଛାତ୍ରବୃତ୍ତି ପାଇଁ ପଞ୍ଜୀକରଣ କରନ୍ତୁ",
        "modal-father-name": "ପିତାଙ୍କ ନାମ",
        "modal-father-mobile-number":"ପିତାଙ୍କ ଯୋଗାଯୋଗ ନମ୍ବର",
        "modal-child-name":"ଶିଶୁର ନାମ",
        "modal-child-school-name": "ବିଦ୍ୟାଳୟର ନାମ",
        "modal-child-class": "ଶ୍ରେଣୀ",
        "modal-address-city": "ସହର",
        "modal-address-state": "ରାଜ୍ୟ",
        "modal-address-pincode": "ପିନ୍ କୋଡ୍",
        "modal-marksheet":"ମାର୍କସିଟ୍ ଅପଲୋଡ୍ କରନ୍ତୁ |",
        "modal-admit-card":"ଆଡମିଟ୍ କାର୍ଡ ଅପଲୋଡ୍ କରନ୍ତୁ |",
        "modal-submit":"ଦାଖଲ କରନ୍ତୁ",
        "footer_left": "© 2025 CSR ପଦକ୍ଷେପ | Ebco ଦ୍ୱାରା ପରିଚାଳିତ",
        "footer_contact": "ଆମ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ: abc@ebco.in",
        "footer_tollfree": "ଟୋଲ-ଫ୍ରି: 12345678900"
      }
    };
